---
title: "3 - sugar syrup consumption"
author: "Michelle Z Hotchkiss"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Packages

```{r}
library(tidyverse)
library(ggforce)
library(lme4)
library(lmerTest)
library(performance)
library(emmeans)
library(multcompView)
```

#Load and format data

```{r}
syrup_vol_data <- read.csv("data/volume24_corr.csv")

syrup_vol_data$mc_id <- as.factor(syrup_vol_data$mc_id)
syrup_vol_data$sc_id <- as.factor(syrup_vol_data$sc_id)
syrup_vol_data$age <- as.factor(syrup_vol_data$age)
syrup_vol_data$exposure <- as.factor(syrup_vol_data$exposure)
syrup_vol_data$treatment <- as.factor(syrup_vol_data$treatment)

syrup_vol_data$treatment <- factor(syrup_vol_data$treatment, levels = c("Control", "DMSO", "1ppb", "10 ppb", "100ppb", "800ppb", "Sacrifice"))
syrup_vol_data$treatment <- recode_factor(syrup_vol_data$treatment, Control = "Control", DMSO = "DMSO", `1ppb`="1 ng/mL",`10 ppb`="10 ng/mL",`100ppb`="100 ng/mL",`800ppb`="800 ng/mL")

syrup_vol_data$exposure <- factor(syrup_vol_data$exposure, levels = c("pre", "during", "post"))

syrup_vol_data_fil <-
  syrup_vol_data %>% 
  filter(!is.na(volume24_corr)) %>% 
  filter(!(day=="-6")) %>% 
  filter(!(treatment=="Sacrifice")) %>% 
  filter(!(age=="7")) %>% 
  filter(!(age=="9"))

syrup_vol_data_fil$day_fac <- as.factor(syrup_vol_data_fil$day)
```

#Fig. S1


```{r}
syrup_vol_data_fil %>% 
  group_by(treatment, day, age) %>% 
  summarise(mean = mean(volume24_corr), se = (sd(volume24_corr)/sqrt(10))) %>% 
  ggplot(aes(day, mean, color=treatment)) +
  geom_line()+
  geom_point()+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,
                 position=position_dodge(0.05))+
  theme_classic() +
  theme(
    text = element_text(size = 14), 
    axis.text.x = element_text(vjust=0.3, size = 12, color="black"), 
    axis.ticks.x=element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.text.y = element_text(color="black", size = 10),
    strip.placement = "outside", 
    strip.text.x = element_text( #text in facet labels
      size = 12, color = "black", face = "bold"),
    strip.background = element_rect(#background of facet labels
      color="white", fill="#ffffff", size=1.5),
    panel.spacing.y = unit(2, "lines"),
    legend.position = "right")+
  labs(color = "Treatment")+
   scale_color_met_d("Hiroshige", direction = -1)+
    scale_y_continuous(name ="Volume of Solution \nConsumed Over 24h (mL)")+
  scale_x_continuous(name ="Day")+
  facet_wrap(~age)
```

#Data Analysis

##Model 1: treatment * day * age

```{r}
lm_1 <- lmer(volume24_corr ~ treatment*day_fac*age + (1|sc_id/mc_id), data=syrup_vol_data_fil)

anova(lm_1) #note: this is lmerTest anova which, in this case, is a type III anova for fixed-effects terms with the Satterthwaite method for denominator degrees of freedom

ranova(lm_1)
```

##Model 2: day * age 

```{r}
lm_2 <- lmer(volume24_corr ~ day_fac + age + day_fac:age + (1|sc_id/mc_id), data=syrup_vol_data_fil)

anova(lm_2)
ranova(lm_2)

check_model(lm_2)
```

#Post-hoc tests

```{r}
lm_2_posthoc_means <- emmeans(lm_2, specs = ~day_fac:age)
lm_2_posthoc_means

lm_2_posthoc_means_age <- emmeans(lm_2, specs = ~age)
lm_2_posthoc_means_age

lm_2_posthoc_means_day <- emmeans(lm_2, specs = ~day_fac)
lm_2_posthoc_means_day
```


```{r}
#Define what each day/age combination is in the vector

DN51 = c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN41 = c(0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN31 = c(0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN21 = c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN11 = c(0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D01 = c(0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D11 = c(0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D21 = c(0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D31 = c(0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D41 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D51 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D61 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D71 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D81 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D91 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D101 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D111 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D121 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D131 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D141 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)


DN53 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN43 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN33 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN23 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

DN13 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D03 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D13 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D23 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D33 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D43 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,0, 0, 0, 0, 0, 0, 0, 0, 0)

D53 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0)

D63 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)

D73 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0)

D83 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0)

D93 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0)

D103 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0)

D113 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0)

D123 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0)

D133 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0)

D143 = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)

pwpp_comparisons <- 
    list("-5 1 to -4 1"= DN51-DN41,
         "-5 1 to -3 1" = DN51-DN31,
         "-5 1 to -2 1" = DN51-DN21,
         "-5 1 to -1 1" = DN51-DN11,
         "-5 1 to 0 1" = DN51-D01,
         "-5 1 to 1 1" = DN51-D11,
         "-5 1 to 2 1" = DN51-D21,
         "-5 1 to 3 1" = DN51-D31,
         "-5 1 to 4 1" = DN51-D41,
         "-5 1 to 5 1" = DN51-D51,
         "-5 1 to 6 1" = DN51-D61,
         "-5 1 to 7 1" = DN51-D71,
         "-5 1 to 8 1" = DN51-D81,
         "-5 1 to 9 1" = DN51-D91,
         "-5 1 to 10 1" = DN51-D101,
         "-5 1 to 11 1" = DN51-D111,
         "-5 1 to 12 1" = DN51-D121,
         "-5 1 to 13 1" = DN51-D131,
         "-5 1 to 14 1" = DN51-D141,
         "-5 1 to -5 3" = DN51-DN53,
         "-4 1 to -3 1" = DN41-DN31,
         "-4 1 to -2 1" = DN41-DN21,
         "-4 1 to -1 1" = DN41-DN11,
         "-4 1 to 0 1" = DN41-D01,
         "-4 1 to 1 1" = DN41-D11,
         "-4 1 to 2 1" = DN41-D21,
         "-4 1 to 3 1" = DN41-D31,
         "-4 1 to 4 1" = DN41-D41,
         "-4 1 to 5 1" = DN41-D51,
         "-4 1 to 6 1" = DN41-D61,
         "-4 1 to 7 1" = DN41-D71,
         "-4 1 to 8 1" = DN41-D81,
         "-4 1 to 9 1" = DN41-D91,
         "-4 1 to 10 1" = DN41-D101,
         "-4 1 to 11 1" = DN41-D111,
         "-4 1 to 12 1" = DN41-D121,
         "-4 1 to 13 1" = DN41-D131,
         "-4 1 to 14 1" = DN41-D141,
         "-4 1 to -4 3" = DN41-DN43,
         "-3 1 to -2 1" = DN31-DN21,
         "-3 1 to -1 1" = DN31-DN11,
         "-3 1 to 0 1" = DN31-D01,
         "-3 1 to 1 1" = DN31-D11,
         "-3 1 to 2 1" = DN31-D21,
         "-3 1 to 3 1" = DN31-D31,
         "-3 1 to 4 1" = DN31-D41,
         "-3 1 to 5 1" = DN31-D51,
         "-3 1 to 6 1" = DN31-D61,
         "-3 1 to 7 1" = DN31-D71,
         "-3 1 to 8 1" = DN31-D81,
         "-3 1 to 9 1" = DN31-D91,
         "-3 1 to 10 1" = DN31-D101,
         "-3 1 to 11 1" = DN31-D111,
         "-3 1 to 12 1" = DN31-D121,
         "-3 1 to 13 1" = DN31-D131,
         "-3 1 to 14 1" = DN31-D141,
         "-3 1 to -3 3" = DN31-DN33,
         "-2 1 to -1 1" = DN21-DN11,
         "-2 1 to 0 1" = DN21-D01,
         "-2 1 to 1 1" = DN21-D11,
         "-2 1 to 2 1" = DN21-D21,
         "-2 1 to 3 1" = DN21-D31,
         "-2 1 to 4 1" = DN21-D41,
         "-2 1 to 5 1" = DN21-D51,
         "-2 1 to 6 1" = DN21-D61,
         "-2 1 to 7 1" = DN21-D71,
         "-2 1 to 8 1" = DN21-D81,
         "-2 1 to 9 1" = DN21-D91,
         "-2 1 to 10 1" = DN21-D101,
         "-2 1 to 11 1" = DN21-D111,
         "-2 1 to 12 1" = DN21-D121,
         "-2 1 to 13 1" = DN21-D131,
         "-2 1 to 14 1" = DN21-D141,
         "-2 1 to -2 3" = DN21-DN23,
         "-1 1 to 0 1" = DN11-D01,
         "-1 1 to 0 1" = DN11-D11,
         "-1 1 to 2 1" = DN11-D21,
         "-1 1 to 3 1" = DN11-D31,
         "-1 1 to 4 1" = DN11-D41,
         "-1 1 to 5 1" = DN11-D51,
         "-1 1 to 6 1" = DN11-D61,
         "-1 1 to 7 1" = DN11-D71,
         "-1 1 to 8 1" = DN11-D81,
         "-1 1 to 9 1" = DN11-D91,
         "-1 1 to 10 1" = DN11-D101,
         "-1 1 to 11 1" = DN11-D111,
         "-1 1 to 12 1" = DN11-D121,
         "-1 1 to 13 1" = DN11-D131,
         "-1 1 to 14 1" = DN11-D141,
         "-1 1 to -1 3" = DN11-DN13,
        "0 1 to 1 1" = D01-D11,
        "0 1 to 2 1" = D01-D21,
        "0 1 to 3 1" = D01-D31,
        "0 1 to 4 1" = D01-D41,
        "0 1 to 5 1" = D01-D51,
        "0 1 to 6 1" = D01-D61,
        "0 1 to 7 1" = D01-D71,
        "0 1 to 8 1" = D01-D81,
        "0 1 to 9 1" = D01-D91,
        "0 1 to 10 1" = D01-D101,
        "0 1 to 11 1" = D01-D111,
        "0 1 to 12 1" = D01-D121,
        "0 1 to 13 1" = D01-D131,
        "0 1 to 14 1" = D01-D141,
        "0 1 to 0 3" = D01-D03,
        "1 1 to 2 1" = D11-D21,
        "1 1 to 3 1" = D11-D31,
        "1 1 to 4 1" = D11-D41,
        "1 1 to 5 1" = D11-D51,
        "1 1 to 6 1" = D11-D61,
        "1 1 to 7 1" = D11-D71,
        "1 1 to 8 1" = D11-D81,
        "1 1 to 9 1" = D11-D91,
        "1 1 to 10 1" = D11-D101,
        "1 1 to 11 1" = D11-D111,
        "1 1 to 12 1" = D11-D121,
        "1 1 to 13 1" = D11-D131,
        "1 1 to 14 1" = D11-D141,
        "1 1 to 1 3" = D11-D13,
        "2 1 to  3 1" = D21-D31,
        "2 1 to  4 1" = D21-D41,
        "2 1 to  5 1" = D21-D51,
        "2 1 to  6 1" = D21-D61,
        "2 1 to  7 1" = D21-D71,
        "2 1 to  8 1" = D21-D81,
        "2 1 to  9 1" = D21-D91,
        "2 1 to  10 1" = D21-D101,
        "2 1 to  11 1" = D21-D111,
        "2 1 to  12 1" = D21-D121,
        "2 1 to  13 1" = D21-D131,
        "2 1 to  14 1" = D21-D141,
        "2 1 to 2 3" = D21-D23,
        "3 1 to  4 1" = D31-D41,
        "3 1 to  5 1" = D31-D51,
        "3 1 to  6 1" = D31-D61,
        "3 1 to  7 1" = D31-D71,
        "3 1 to  8 1" = D31-D81,
        "3 1 to  9 1" = D31-D91,
        "3 1 to  10 1" = D31-D101,
        "3 1 to  11 1" = D31-D111,
        "3 1 to  12 1" = D31-D121,
        "3 1 to  13 1" = D31-D131,
        "3 1 to  14 1" = D31-D141,
        "3 1 to 3 3" = D31-D33,
        "4 1 to  5 1" = D41-D51,
        "4 1 to  6 1" = D41-D61,
        "4 1 to  7 1" = D41-D71,
        "4 1 to  8 1" = D41-D81,
        "4 1 to  9 1" = D41-D91,
        "4 1 to  10 1" = D41-D101,
        "4 1 to  11 1" = D41-D111,
        "4 1 to  12 1" = D41-D121,
        "4 1 to  13 1" = D41-D131,
        "4 1 to  14 1" = D41-D141,
        "4 1 to 4 3" = D41-D43,
        "5 1 to  6 1" = D51-D61,
        "5 1 to  7 1" = D51-D71,
        "5 1 to  8 1" = D51-D81,
        "5 1 to  9 1" = D51-D91,
        "5 1 to  10 1" = D51-D101,
        "5 1 to  11 1" = D51-D111,
        "5 1 to  12 1" = D51-D121,
        "5 1 to  13 1" = D51-D131,
        "5 1 to  14 1" = D51-D141,
        "5 1 to 5 3"= D51-D53,
        "6 1 to  7 1" = D61-D71,
        "6 1 to  8 1" = D61-D81,
        "6 1 to  9 1" = D61-D91,
        "6 1 to  10 1" = D61-D101,
        "6 1 to  11 1" = D61-D111,
        "6 1 to  12 1" = D61-D121,
        "6 1 to  13 1" = D61-D131,
        "6 1 to  14 1" = D61-D141,
        "6 1 to 6 3" = D61-D63,
        "7 1 to  8 1" = D71-D81,
        "7 1 to  9 1" = D71-D91,
        "7 1 to  10 1" = D71-D101,
        "7 1 to  11 1" = D71-D111,
        "7 1 to  12 1" = D71-D121,
        "7 1 to  13 1" = D71-D131,
        "7 1 to  14 1" = D71-D141,
        "7 1 to 7 3" = D71-D73,
        "8 1 to 9 1" = D81-D91,
        "8 1 to 10 1" = D81-D101,
        "8 1 to 11 1" = D81-D111,
        "8 1 to 12 1" = D81-D121,
        "8 1 to 13 1" = D81-D131,
        "8 1 to 14 1" = D81-D141,
        "8 1 to 8 3" = D81-D83,
        "9 1 to  10 1" = D91-D101,
        "9 1 to  11 1" = D91-D111,
        "9 1 to  12 1" = D91-D121,
        "9 1 to  13 1" = D91-D131,
        "9 1 to  14 1" = D91-D141,
        "9 1 to 9 3" = D91-D93,
        "10 1 to  11 1" = D101-D111,
        "10 1 to  12 1" = D101-D121,
        "10 1 to  13 1" = D101-D131,
        "10 1 to  14 1" = D101-D141,
        "10 1 to 10 3" = D101-D103,
        "11 1 to  12 1" = D111-D121,
        "11 1 to  13 1" = D111-D131,
        "11 1 to  14 1" = D111-D141,
        "11 1 to 11 3" = D111-D113,
        "12 1 to  13 1" = D121-D131,
        "12 1 to  14 1" = D121-D141,
        "12 1 to 12 3" = D121-D123,
        "13 1 to 14 1" = D131-D141,
        "13 1 to 13 3" = D131-D133,
        "14 1 to 14 3" = D141-D143,
        "-5 3 to  -4 3" = DN53-DN43,
        "-5 3 to  -3 3" = DN53-DN33,
        "-5 3 to  -2 3" = DN53-DN23,
        "-5 3 to  -1 3" = DN53-DN13,
        "-5 3 to  0 3" = DN53-D03,
        "-5 3 to  1 3" = DN53-D13,
        "-5 3 to  2 3" = DN53-D23,
        "-5 3 to  3 3" = DN53-D33,
        "-5 3 to  4 3" = DN53-D43,
        "-5 3 to  5 3" = DN53-D53,
        "-5 3 to  6 3" = DN53-D63,
        "-5 3 to  7 3" = DN53-D73,
        "-5 3 to  8 3" = DN53-D83,
        "-5 3 to  9 3" = DN53-D93,
        "-5 3 to  10 3" = DN53-D103,
        "-5 3 to  11 3" = DN53-D113,
        "-5 3 to  12 3" = DN53-D123,
        "-5 3 to  13 3" = DN53-D133,
        "-5 3 to  14 3" = DN53-D143,
        "-4 3 to  -3 3" = DN43-DN33,
        "-4 3 to  -2 3" = DN43-DN23,
        "-4 3 to  -1 3" = DN43-DN13,
        "-4 3 to  0 3" = DN43-D03,
        "-4 3 to  1 3" = DN43-D13,
        "-4 3 to  2 3" = DN43-D23,
        "-4 3 to  3 3" = DN43-D33,
        "-4 3 to  4 3" = DN43-D43,
        "-4 3 to  5 3" = DN43-D53,
        "-4 3 to  6 3" = DN43-D63,
        "-4 3 to  7 3" = DN43-D73,
        "-4 3 to  8 3" = DN43-D83,
        "-4 3 to  9 3" = DN43-D93,
        "-4 3 to  10 3" = DN43-D103,
        "-4 3 to  11 3" = DN43-D113,
        "-4 3 to  12 3" = DN43-D123,
        "-4 3 to  13 3" = DN43-D133,
        "-4 3 to  14 3" = DN43-D143,
        "-3 3 to  -2 3" = DN33-DN23,
        "-3 3 to  -1 3" = DN33-DN13,
        "-3 3 to  0 3" = DN33-D03,
        "-3 3 to  1 3" = DN33-D13,
        "-3 3 to  2 3" = DN33-D23,
        "-3 3 to  3 3" = DN33-D33,
        "-3 3 to  4 3" = DN33-D43,
        "-3 3 to  5 3" = DN33-D53,
        "-3 3 to  6 3" = DN33-D63,
        "-3 3 to  7 3" = DN33-D73,
        "-3 3 to  8 3" = DN33-D83,
        "-3 3 to  9 3" = DN33-D93,
        "-3 3 to  10 3" = DN33-D103,
        "-3 3 to  11 3" = DN33-D113,
        "-3 3 to  12 3" = DN33-D123,
        "-3 3 to  13 3" = DN33-D133,
        "-3 3 to  14 3" = DN33-D143,
        "-2 3 to  -1 3" = DN23-DN13,
        "-2 3 to  0 3" = DN23-D03,
        "-2 3 to  1 3" = DN23-D13,
        "-2 3 to  2 3" = DN23-D23,
        "-2 3 to  3 3" = DN23-D33,
        "-2 3 to  4 3" = DN23-D43,
        "-2 3 to  5 3" = DN23-D53,
        "-2 3 to  6 3" = DN23-D63,
        "-2 3 to  7 3" = DN23-D73,
        "-2 3 to  8 3" = DN23-D83,
        "-2 3 to  9 3" = DN23-D93,
        "-2 3 to  10 3" = DN23-D103,
        "-2 3 to  11 3" = DN23-D113,
        "-2 3 to  12 3" = DN23-D123,
        "-2 3 to  13 3" = DN23-D133,
        "-2 3 to  14 3" = DN23-D143,
        "-1 3 to  0 3" = DN13-D03,
        "-1 3 to  1 3" = DN13-D13,
        "-1 3 to  2 3" = DN13-D23,
        "-1 3 to  3 3" = DN13-D33,
        "-1 3 to  4 3" = DN13-D43,
        "-1 3 to  5 3" = DN13-D53,
        "-1 3 to  6 3" = DN13-D63,
        "-1 3 to  7 3" = DN13-D73,
        "-1 3 to  8 3" = DN13-D83,
        "-1 3 to  9 3" = DN13-D93,
        "-1 3 to  10 3" = DN13-D103,
        "-1 3 to  11 3" = DN13-D113,
        "-1 3 to  12 3" = DN13-D123,
        "-1 3 to  13 3" = DN13-D133,
        "-1 3 to  14 3" = DN13-D143,
        "0 3 to  1 3" = D03-D13,
        "0 3 to  2 3" = D03-D23,
        "0 3 to  3 3" = D03-D33,
        "0 3 to  4 3" = D03-D43,
        "0 3 to  5 3" = D03-D53,
        "0 3 to  6 3" = D03-D63,
        "0 3 to  7 3" = D03-D73,
        "0 3 to  8 3" = D03-D83,
        "0 3 to  9 3" = D03-D93,
        "0 3 to  10 3" = D03-D103,
        "0 3 to  11 3" = D03-D113,
        "0 3 to  12 3" = D03-D123,
        "0 3 to  13 3" = D03-D133,
        "0 3 to  14 3" = D03-D143,
        "1 3 to  2 3" = D13-D23,
        "1 3 to  3 3" = D13-D33,
        "1 3 to  4 3" = D13-D43,
        "1 3 to  5 3" = D13-D53,
        "1 3 to  6 3" = D13-D63,
        "1 3 to  7 3" = D13-D73,
        "1 3 to  8 3" = D13-D83,
        "1 3 to  9 3" = D13-D93,
        "1 3 to  10 3" = D13-D103,
        "1 3 to  11 3" = D13-D113,
        "1 3 to  12 3" = D13-D123,
        "1 3 to  13 3" = D13-D133,
        "1 3 to  14 3" = D13-D143,
        "2 3 to  3 3" = D23-D33,
        "2 3 to  4 3" = D23-D43,
        "2 3 to  5 3" = D23-D53,
        "2 3 to  6 3" = D23-D63,
        "2 3 to  7 3" = D23-D73,
        "2 3 to  8 3" = D23-D83,
        "2 3 to  9 3" = D23-D93,
        "2 3 to  10 3" = D23-D103,
        "2 3 to  11 3" = D23-D113,
        "2 3 to  12 3" = D23-D123,
        "2 3 to  13 3" = D23-D133,
        "2 3 to  14 3" = D23-D143,
        "3 3 to  4 3" = D33-D43,
        "3 3 to  5 3" = D33-D53,
        "3 3 to  6 3" = D33-D63,
        "3 3 to  7 3" = D33-D73,
        "3 3 to  8 3" = D33-D83,
        "3 3 to  9 3" = D33-D93,
        "3 3 to  10 3" = D33-D103,
        "3 3 to  11 3" = D33-D113,
        "3 3 to  12 3" = D33-D123,
        "3 3 to  13 3" = D33-D133,
        "3 3 to  14 3" = D33-D143,
        "4 3 to  5 3" = D43-D53,
        "4 3 to  6 3" = D43-D63,
        "4 3 to  7 3" = D43-D73,
        "4 3 to  8 3" = D43-D83,
        "4 3 to  9 3" = D43-D93,
        "4 3 to  10 3" = D43-D103,
        "4 3 to  11 3" = D43-D113,
        "4 3 to  12 3" = D43-D123,
        "4 3 to  13 3" = D43-D133,
        "4 3 to  14 3" = D43-D143,
        "5 3 to  6 3" = D53-D63,
        "5 3 to  7 3" = D53-D73,
        "5 3 to  8 3" = D53-D83,
        "5 3 to  9 3" = D53-D93,
        "5 3 to  10 3" = D53-D103,
        "5 3 to  11 3" = D53-D113,
        "5 3 to  12 3" = D53-D123,
        "5 3 to  13 3" = D53-D133,
        "5 3 to  14 3" = D53-D143,
        "6 3 to  7 3" = D63-D73,
        "6 3 to  8 3" = D63-D83,
        "6 3 to  9 3" = D63-D93,
        "6 3 to  10 3" = D63-D103,
        "6 3 to  11 3" = D63-D113,
        "6 3 to  12 3" = D63-D123,
        "6 3 to  13 3" = D63-D133,
        "6 3 to  14 3" = D63-D143,
        "7 3 to  8 3" = D73-D83,
        "7 3 to  9 3" = D73-D93,
        "7 3 to  10 3" = D73-D103,
        "7 3 to  11 3" = D73-D113,
        "7 3 to  12 3" = D73-D123,
        "7 3 to  13 3" = D73-D133,
        "7 3 to  14 3" = D73-D143,
        "8 3 to  9 3" = D83-D93,
        "8 3 to  10 3" = D83-D103,
        "8 3 to  11 3" = D83-D113,
        "8 3 to  12 3" = D83-D123,
        "8 3 to  13 3" = D83-D133,
        "8 3 to  14 3" = D83-D143,
        "9 3 to 10 3" = D93-D103,
        "9 3 to 11 3" = D93-D113,
        "9 3 to 12 3" = D93-D123,
        "9 3 to 13 3" = D93-D133,
        "9 3 to 14 3" = D93-D143,
        "10 3 to 11 3" = D103-D113,
        "10 3 to 12 3" = D103-D123,
        "10 3 to 13 3" = D103-D133,
        "10 3 to 14 3" = D103-D143,
        "11 3 to  12 3" = D113-D123,
        "11 3 to  13 3" = D113-D133,
        "11 3 to  14 3" = D113-D143,
        "12 3 to 13 3" = D123-D133,
        "12 3 to 14 3" = D123-D143,
        "13 3 to 14 3" = D133-D143
       )

str(pwpp_comparisons)
```


```{r}
lm_2_posthoc_comparisons <- contrast(lm_2_posthoc_means, method = pwpp_comparisons, adjust = "sidak")
lm_2_posthoc_comparisons
```


## Fig. S2 - Pairwise P-value Plot

```{r}
lm_2_posthoc_fig <- emmeans(lm_2, ~day_fac:age)
lm_2_posthoc_fig
```

```{r}
pwpp_fig <- 
  pwpp(lm_2_posthoc_fig, method = pwpp_comparisons, adjust = "sidak", type = "response", sort = FALSE, ylab = "Day-Age Combination", xlab = "P-value")+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(color="black"), 
    axis.text.y = element_text(color="black"),
    panel.grid.major.y = element_line(colour="grey80", size=0.3)
  )+
  ggplot2::geom_hline(yintercept = 20.5, linetype = "dashed")+
  facet_zoom(xlim = c(-0.05, 0.05), zoom.size = 1)
  
pwpp_fig

```



